// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceMessageClient is the client API for ServiceMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceMessageClient interface {
	Sayhello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type serviceMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceMessageClient(cc grpc.ClientConnInterface) ServiceMessageClient {
	return &serviceMessageClient{cc}
}

func (c *serviceMessageClient) Sayhello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pozo.ServiceMessage/Sayhello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceMessageServer is the server API for ServiceMessage service.
// All implementations must embed UnimplementedServiceMessageServer
// for forward compatibility
type ServiceMessageServer interface {
	Sayhello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedServiceMessageServer()
}

// UnimplementedServiceMessageServer must be embedded to have forward compatible implementations.
type UnimplementedServiceMessageServer struct {
}

func (UnimplementedServiceMessageServer) Sayhello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sayhello not implemented")
}
func (UnimplementedServiceMessageServer) mustEmbedUnimplementedServiceMessageServer() {}

// UnsafeServiceMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceMessageServer will
// result in compilation errors.
type UnsafeServiceMessageServer interface {
	mustEmbedUnimplementedServiceMessageServer()
}

func RegisterServiceMessageServer(s grpc.ServiceRegistrar, srv ServiceMessageServer) {
	s.RegisterService(&ServiceMessage_ServiceDesc, srv)
}

func _ServiceMessage_Sayhello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMessageServer).Sayhello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pozo.ServiceMessage/Sayhello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMessageServer).Sayhello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceMessage_ServiceDesc is the grpc.ServiceDesc for ServiceMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pozo.ServiceMessage",
	HandlerType: (*ServiceMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sayhello",
			Handler:    _ServiceMessage_Sayhello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pozo.proto",
}
