// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/lider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Time    int32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Ganador bool  `protobuf:"varint,3,opt,name=ganador,proto3" json:"ganador,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Status) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Status) GetGanador() bool {
	if x != nil {
		return x.Ganador
	}
	return false
}

type Playermove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move int32 `protobuf:"varint,1,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *Playermove) Reset() {
	*x = Playermove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Playermove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playermove) ProtoMessage() {}

func (x *Playermove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playermove.ProtoReflect.Descriptor instead.
func (*Playermove) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{2}
}

func (x *Playermove) GetMove() int32 {
	if x != nil {
		return x.Move
	}
	return 0
}

type Nextgame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer int32 `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Nextgame) Reset() {
	*x = Nextgame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nextgame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nextgame) ProtoMessage() {}

func (x *Nextgame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nextgame.ProtoReflect.Descriptor instead.
func (*Nextgame) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{3}
}

func (x *Nextgame) GetAnswer() int32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

type Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Amount) Reset() {
	*x = Amount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{4}
}

func (x *Amount) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{5}
}

func (x *Msg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_lider_proto protoreflect.FileDescriptor

var file_proto_lider_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x61, 0x6e, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67,
	0x61, 0x6e, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x22, 0x0a, 0x08, 0x4e, 0x65, 0x78, 0x74,
	0x67, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x1f, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb9, 0x03,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x0e, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12,
	0x0b, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0d, 0x2e, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x2c, 0x0a,
	0x06, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x31, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0e, 0x53,
	0x69, 0x67, 0x75, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x6a, 0x75, 0x65, 0x67, 0x6f, 0x12, 0x0b, 0x2e,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0f, 0x2e, 0x6c, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a,
	0x09, 0x50, 0x65, 0x64, 0x69, 0x72, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x0a, 0x2e, 0x6c, 0x69, 0x64,
	0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0e, 0x53, 0x65, 0x53, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x6f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x0b, 0x2e, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0b, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0b, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x4e,
	0x61, 0x6d, 0x65, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x41, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0d, 0x4d, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x41, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x32, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0x0a, 0x2e, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0e, 0x52, 0x65,
	0x74, 0x6f, 0x72, 0x6e, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x0a, 0x2e, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lider_proto_rawDescOnce sync.Once
	file_proto_lider_proto_rawDescData = file_proto_lider_proto_rawDesc
)

func file_proto_lider_proto_rawDescGZIP() []byte {
	file_proto_lider_proto_rawDescOnce.Do(func() {
		file_proto_lider_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lider_proto_rawDescData)
	})
	return file_proto_lider_proto_rawDescData
}

var file_proto_lider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_lider_proto_goTypes = []interface{}{
	(*Name)(nil),       // 0: lider.Name
	(*Status)(nil),     // 1: lider.Status
	(*Playermove)(nil), // 2: lider.Playermove
	(*Nextgame)(nil),   // 3: lider.Nextgame
	(*Amount)(nil),     // 4: lider.Amount
	(*Msg)(nil),        // 5: lider.Msg
}
var file_proto_lider_proto_depIdxs = []int32{
	0, // 0: lider.StartServer.AgregarJugador:input_type -> lider.Name
	2, // 1: lider.StartServer.Juego1:input_type -> lider.Playermove
	0, // 2: lider.StartServer.Siguientejuego:input_type -> lider.Name
	5, // 3: lider.StartServer.PedirPozo:input_type -> lider.Msg
	0, // 4: lider.StartServer.SeSolicitoPozo:input_type -> lider.Name
	0, // 5: lider.StartServer.EstadoLider:input_type -> lider.Name
	2, // 6: lider.StartServer.MandarALider:input_type -> lider.Playermove
	2, // 7: lider.StartServer.MandarALider2:input_type -> lider.Playermove
	5, // 8: lider.StartServer.RetornarEstado:input_type -> lider.Msg
	1, // 9: lider.StartServer.AgregarJugador:output_type -> lider.Status
	1, // 10: lider.StartServer.Juego1:output_type -> lider.Status
	3, // 11: lider.StartServer.Siguientejuego:output_type -> lider.Nextgame
	4, // 12: lider.StartServer.PedirPozo:output_type -> lider.Amount
	4, // 13: lider.StartServer.SeSolicitoPozo:output_type -> lider.Amount
	1, // 14: lider.StartServer.EstadoLider:output_type -> lider.Status
	1, // 15: lider.StartServer.MandarALider:output_type -> lider.Status
	5, // 16: lider.StartServer.MandarALider2:output_type -> lider.Msg
	1, // 17: lider.StartServer.RetornarEstado:output_type -> lider.Status
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lider_proto_init() }
func file_proto_lider_proto_init() {
	if File_proto_lider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Playermove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nextgame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lider_proto_goTypes,
		DependencyIndexes: file_proto_lider_proto_depIdxs,
		MessageInfos:      file_proto_lider_proto_msgTypes,
	}.Build()
	File_proto_lider_proto = out.File
	file_proto_lider_proto_rawDesc = nil
	file_proto_lider_proto_goTypes = nil
	file_proto_lider_proto_depIdxs = nil
}
